---

- name: Ensure the molecule install directory exists
  file:
    path: "{{ molecule_install_dir }}"
    state: directory

- name: Ensure the azure-cli bin directory exists
  file:
    path: "{{ molecule_bin_dir }}"
    state: directory
  when: molecule_install_venv_helper is defined
        and molecule_install_venv_helper

- name: Ensure Python 3 interpreter is used by Ansible
  set_fact:
    ansible_python_interpreter: "{{ molecule_python3_path }}"

- name: Ensure molecule is installed in a virtual environment
  pip:
    name: "{{ item }}"
    version: "{{ molecule_version }}"
    state: present
    virtualenv: "{{ molecule_install_dir }}/molecule-{{ molecule_version }}"
    virtualenv_command: "{{ molecule_python3_path }} -m venv"
    virtualenv_site_packages: "{{ molecule_venv_site_packages | default(False) }}"
  loop:
    - molecule
    - molecule[docker]

- name: Ensure the originally configured Python interpreter is used by Ansible
  set_fact:
    ansible_python_interpreter: "{{ molecule_ansible_python_interpreter }}"
  when: molecule_ansible_python_interpreter is defined

- name: Ensure the current release is symlinked in the install directory
  file:
    src: "{{ molecule_install_dir }}/molecule-{{ molecule_version }}"
    dest: "{{ molecule_install_dir }}/{{ molecule_current_dirname }}"
    state: link

- name: Ensure venv wrapper exists in virtualenv bin directory
  template:
    src: venv.sh.j2
    dest: "{{ molecule_install_dir }}/molecule-{{ molecule_version }}/bin/venv"
    mode: 0755
  loop:
    - python

- name: Ensure venv helper exists for executables in bin directory
  template:
    src: venv.sh.j2
    dest: "{{ molecule_bin_dir }}/{{ item }}"
    mode: 0755
  loop:
    - anyconfig_cli
    - chardetect
    - cookiecutter
    - flake8
    - gilt
    - identify-cli
    - molecule
    - nodeenv
    - pre-commit
    - pre-commit-validate-config
    - pre-commit-validate-manifest
    - pycodestyle
    - pyflakes
    - py.test
    - pytest
    - slugify
    - tabulate
    - virtualenv
    - yamllint
  when: molecule_install_venv_helper is defined
        and molecule_install_venv_helper
