---

- import_tasks: pre-checks-os.yml

- include_tasks: "{{ ansible_os_family | lower }}/install-os-dependencies.yml"
  when: molecule_install_os_dependencies is defined
        and molecule_install_os_dependencies

- import_tasks: pre-checks-environment.yml

- import_tasks: get-version.yml
  when: molecule_version is not defined
        or not molecule_version

- import_tasks: install-molecule.yml

- import_tasks: post-checks-environment.yml
