---

- name: Check to see if the molecule version directory exists
  stat:
    path: "{{ molecule_install_dir }}/{{ molecule_venv_name }}-{{ molecule_venv_suffix }}"
  register: molecule_check_version_dir

- name: Fail if the molecule version directory doesn't exist
  fail:
    msg: "{{ molecule_install_dir }}/{{ molecule_venv_name }}-{{ molecule_venv_suffix }} is missing after play."
  when: not molecule_check_version_dir.stat.exists

- name: Check to see if the molecule current symlink exists
  stat:
    path: "{{ molecule_install_dir }}/{{ molecule_venv_name }}"
  register: molecule_check_symlink_dir

- name: Fail if the molecule symlink directory doesn't exist
  fail:
    msg: "{{ molecule_install_dir }}/{{ molecule_venv_name }} symlink not correct after play."
  when: not molecule_check_symlink_dir.stat.exists
        or not molecule_check_symlink_dir.stat.islnk
        or molecule_check_symlink_dir.stat.lnk_target != (molecule_install_dir + "/" + molecule_venv_name + "-" + molecule_venv_suffix)

- name: Check to see if the molecule version directory is a virtualenv
  stat:
    path: "{{ molecule_install_dir }}/{{ molecule_venv_name }}/bin/activate"
  register: molecule_check_virtualenv_dir

- name: Fail if the molecule virtualenv directory doesn't exist
  fail:
    msg: "{{ molecule_install_dir }}/{{ molecule_venv_name }}/bin/activate not found after play."
  when: not molecule_check_virtualenv_dir.stat.exists
        or not molecule_check_virtualenv_dir.stat.isreg
