---
- name: Converge
  hosts: all
  become: true
  vars:
    molecule_install_os_dependencies: true
    molecule_install_dir: /opt/molecule/bin
    molecule_bin_dir: /usr/bin
    molecule_venv_name: current
    molecule_support_packages:
      - docker
      - lint
  roles:
    - role: xanmanning.molecule
